<?php
global $post;
$id = $post->ID;
$title = $post->post_title;
$slug = $post->post_name;
$lead = get_field( 'lead_text', $id );
$about = get_field( 'about_text', $id );
$steering_committee = get_field( '', $id );
echo '<div class="row thirds">';
	echo '<div class="cell one">';
		echo '<div class="text">';
			echo '<h3>' . $lead . '</h3>';
		echo '</div>';
	echo '</div>';
	echo '<div class="cell two">';
		echo '<div class="text">';
			echo $about;
		echo '</div>';
	echo '</div>';
echo '</div>';
echo '<div class="row thirds">';
	echo '<div class="cell one">';
		echo '<div class="text">';
			echo '<h3>La Casita Verde Steering Committee</h3>';
		echo '</div>';
	echo '</div>';
	echo '<div class="cell two">';
		echo '<div class="text">';
			echo '<ul>';
				while ( have_rows( 'steering_committee', $id ) ) : the_row();
					$name = get_sub_field( 'name', $id );
					$role = get_sub_field( 'role', $id );
					echo '<li>' . $name . ', ' . $role .  '</li>';
				endwhile;
			echo '</ul>';
		echo '</div>';
	echo '</div>';
echo '</div>';
?>